### ISSUE TITLE
IP changes every minute

### ISSUE THREAD

**Issue by sssseossss** [ruped24/toriptables2#8]
Thanks for a quick response. One more question:
I can see that my IP appears changing every minute or so. Looking into your script there is nothing what suggests this change. Is this Tor setup? Is there a way to stop changing IP. 
Sorry if the questions is off-topic in this thread.

**Comment by ruped24** [comment]
Short answer is No.
You are making tcp/9040 connections to the remote host.  
So that's done by Tor's back-end circuitry.  You can't request a static IP, hence it changes...

Good question.
I can't be 100% sure.  If what you are asking is possible.  
But the script don't change your IP.  It connects you to Tor network then gets out of the way.

I hope that help.
